"""journal user_id fk on delete cascade

Revision ID: b50da835b699
Revises: 093ee79a80fc
Create Date: 2026-08-02 00:32:33.692892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50da835b699'
down_revision: Union[str, Sequence[str], None] = '093ee79a80fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_ibfk_1', 'journal', type_='foreignkey')
    op.create_foreign_key('fk_journal_user_id', 'journal', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_journal_user_id', 'journal', type_='foreignkey')
    op.create_foreign_key('journal_ibfk_1', 'journal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
