apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysqld-exporter
  labels:
    app: mysqld-exporter
spec:
  selector:
    matchLabels:
      app: mysqld-exporter
  sampleLimit: 10000
  endpoints:
    - port: metrics
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: mysql
