apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrate
  labels:
    app: api-migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: api-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          command: ["alembic", "-c", "/api/alembic.ini", "upgrade", "head"]
          envFrom:
            - configMapRef:
                name: journal-app-config
            - secretRef:
                name: journal-app-secrets
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              memory: {{ .Values.api.resources.limits.memory }}
