apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  sampleLimit: 10000
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      relabelings:
        - targetLabel: job
          replacement: journal-api
