name: journal
volumes:
  mysql-main:

services:
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    volumes: 
    - mysql-main:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  elasticmq:
    image: softwaremill/elasticmq-native:latest
    ports:
    - 9324:9324
    - 9325:9325
    volumes:
    - ./elasticmq.conf:/opt/elasticmq.conf
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9324"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    ports:
    - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  api:
    build: ./api
    volumes:
    - ./api:/api
    ports:
    - 8000:8000
    entrypoint: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
    - .env
    depends_on:
      mysql:
        condition: service_healthy
      elasticmq:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  worker:
    image: steffenp123/journal-worker:latest
    restart: on-failure
    env_file:
    - .env
    depends_on:
      elasticmq:
        condition: service_healthy