volumes:
  mysql-main:

services:
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    volumes: 
    - mysql-main:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  core:
    build: .
    volumes:
    - .:/src
    ports: 
    - 8000:8000
    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
    - .env
    depends_on: 
      mysql:
        condition: service_healthy