volumes:
  mysql-main:

services:
  mysql:
    image: mysql:latest
    ports:
    - 3306:3306
    volumes: 
    - mysql-main:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  journal-app:
    image: steffenp123/journal-app:latest
    ports: 
    - 8000:8000
    env_file: .env
    depends_on: 
      mysql:
        condition: service_healthy