include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
}

queues {
  email-verification {
    defaultVisibilityTimeout = 30 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "email-verification-dlq"
      maxReceiveCount = 3
    }
  }
  email-verification-dlq { }
}
