global:
  scrape_interval: 15s

scrape_configs:
  - job_name: journal-api
    sample_limit: 10000
    label_limit: 20
    static_configs:
      - targets: ["api:8000"]

  - job_name: redis
    sample_limit: 10000
    label_limit: 20
    static_configs:
      - targets: ["redis-exporter:9121"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  - job_name: mysql
    sample_limit: 10000
    label_limit: 20
    static_configs:
      - targets: ["mysqld-exporter:9104"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop

  - job_name: prometheus
    sample_limit: 10000
    label_limit: 20
    static_configs:
      - targets: ["localhost:9090"]
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: go_.*
        action: drop
