apiVersion: v1
kind: ConfigMap
metadata:
  name: journal-app-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  VERIFY_API_URL: {{ printf "https://%s/verify-email" .Values.ingress.host | quote }}
