apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: journal-app-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: journal-app-secrets
  data:
    - secretKey: DB_MASTER_SECRET
      remoteRef:
        key: {{ .Values.secrets.dbSecretArn }}
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: {{ .Values.secrets.jwtSecretArn }}
