apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: cluster-autoscaler
    spec:
      project: default
      source:
        repoURL: {{ .Values.clusterAutoscaler.repoURL }}
        chart: {{ .Values.clusterAutoscaler.chart }}
        targetRevision: {{ .Values.clusterAutoscaler.version }}
        helm:
          releaseName: cluster-autoscaler
          valuesObject:
            autoDiscovery:
              clusterName: '{{`{{.metadata.annotations.cluster_name}}`}}'
            awsRegion: '{{`{{.metadata.annotations.region}}`}}'
            image:
              tag: {{ .Values.clusterAutoscaler.imageTag }}
            rbac:
              serviceAccount:
                name: cluster-autoscaler
            extraArgs:
              skip-nodes-with-system-pods: false
      destination:
        name: '{{`{{.name}}`}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
