apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: external-secrets
    spec:
      project: default
      source:
        repoURL: {{ .Values.externalSecrets.repoURL }}
        chart: {{ .Values.externalSecrets.chart }}
        targetRevision: {{ .Values.externalSecrets.version }}
        helm:
          releaseName: external-secrets
          valuesObject:
            serviceAccount:
              name: external-secrets
            nodeSelector:
              {{- toYaml .Values.control.nodeSelector | nindent 14 }}
            tolerations:
              {{- toYaml .Values.control.tolerations | nindent 14 }}
            webhook:
              nodeSelector:
                {{- toYaml .Values.control.nodeSelector | nindent 16 }}
              tolerations:
                {{- toYaml .Values.control.tolerations | nindent 16 }}
            certController:
              nodeSelector:
                {{- toYaml .Values.control.nodeSelector | nindent 16 }}
              tolerations:
                {{- toYaml .Values.control.tolerations | nindent 16 }}
      destination:
        name: '{{`{{.name}}`}}'
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
