apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keda
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: keda
    spec:
      project: default
      source:
        repoURL: {{ .Values.keda.repoURL }}
        chart: {{ .Values.keda.chart }}
        targetRevision: {{ .Values.keda.version }}
        helm:
          releaseName: keda
          valuesObject:
            nodeSelector:
              {{- toYaml .Values.control.nodeSelector | nindent 14 }}
            tolerations:
              {{- toYaml .Values.control.tolerations | nindent 14 }}
      destination:
        name: '{{`{{.name}}`}}'
        namespace: keda
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: -1
