apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp-deployment
  labels:
    app: temp
spec:
  selector:
    matchLabels:
      app: temp
  replicas: 2
  template:
    metadata:
      name: temp-pod
      labels:
        app: temp
    spec:
      containers:
      - name: temp-container
        image: softwaremill/elasticmq-native:latest