
control:
  nodeSelector:
    node-role: control
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

awsLoadBalancerController:
  repoURL: https://aws.github.io/eks-charts
  chart: aws-load-balancer-controller
  version: 3.5.0

certManager:
  repoURL: https://charts.jetstack.io
  chart: cert-manager
  version: v1.21.2

keda:
  repoURL: https://kedacore.github.io/charts
  chart: keda
  version: 2.21.0

karpenter:
  repoURL: public.ecr.aws/karpenter
  chart: karpenter
  version: 1.14.1

karpenterNodePool:
  repoURL: https://github.com/STEFFENS-GITHUB/journal-app.git
  targetRevision: main
  path: infra/helm/karpenter-nodepool

externalDns:
  repoURL: https://kubernetes-sigs.github.io/external-dns
  chart: external-dns
  version: 1.22.0

externalSecrets:
  repoURL: https://charts.external-secrets.io
  chart: external-secrets
  version: 2.11.0

journalApp:
  repoURL: https://github.com/STEFFENS-GITHUB/journal-app.git
  targetRevision: main
  path: infra/helm/journal-app
