api:
  image:
    repository: steffenp123/journal-api
    tag: latest
  replicas: 2
  port: 8000
  serviceAccountName: api
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

worker:
  image:
    repository: steffenp123/journal-worker
    tag: latest
  replicas: 1
  serviceAccountName: worker
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

ingress:
  host: ""

config:
  AWS_REGION: ""
  DB_ENDPOINT: ""
  DB_NAME: ""
  REDIS_URL: ""
  EMAIL_VERIFICATION_QUEUE_URL: ""
  VERIFY_API_URL: ""

secrets:
  dbSecretArn: ""
  jwtSecretArn: ""
