api:
  image:
    repository: steffenp123/journal-api
    tag: latest
  port: 8000
  serviceAccountName: api
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi
  autoscaling:
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70

worker:
  image:
    repository: steffenp123/journal-worker
    tag: latest
  serviceAccountName: worker
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  autoscaling:
    minReplicaCount: 0
    maxReplicaCount: 5
    queueLength: 5

mysqldExporter:
  image:
    repository: prom/mysqld-exporter
    tag: v0.20.0
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi
