name: Journal App Image Build
on:
  push:
    branches:
    - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Install python to runner
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install app dependancies
      run: pip install -r app/requirements.txt
    - name: Run docker compose
      run: docker compose up -d mysql
    - name: Wait for MySQL DB to be ready
      run: |
        until nc -z 127.0.0.1 3306; do echo "Waiting..."; sleep 2; done
    - name: Run journal-app unit tests
      run: pytest app

  build-and-push:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PAT}}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          steffenp123/journal-app:1.${{ github.run_number }}
          steffenp123/journal-app:latest