name: Journal App Image Build
on:
  push:
    branches:
    - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v6
    - name: Install python to runner
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
    - name: Install app dependancies
      run: pip install -r app/requirements.txt
    - name: Run docker compose
      env:
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DEFAULT_APP_PASSWORD: ${{ secrets.DEFAULT_APP_PASSWORD }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DOCKER_ENV: ${{ secrets.DOCKER_ENV }}
      run: docker compose up -d mysql
    - name: Wait for MySQL DB to be ready
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      run: |
        until docker compose exec -T mysql mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SELECT 1" &>/dev/null; do
          echo "Waiting for MySQL..."
          sleep 2
        done
    - name: Run journal-app unit tests
      run: pytest app

  build-and-push:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4
    - name: Login to Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PAT}}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          steffenp123/journal-app:1.${{ github.run_number }}
          steffenp123/journal-app:latest